#!/usr/bin/env python3

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description="Generate bit field C macros from .def file.")
	parser.add_argument("input_file", type=Path, help="Path to input .def file (the .h is written alongside it)")
	return parser.parse_args()


def build_field_accessor(cur_pos: int, bit_count: int) -> tuple[str, str]:
	getter_parts = []
	setter_parts = []
	pos = cur_pos
	end_pos = cur_pos + bit_count

	while pos < end_pos:
		byte_index = pos // 8
		next_pos = min((byte_index + 1) * 8, end_pos)
		byte_start_pos = pos - byte_index * 8
		byte_end_pos = next_pos - byte_index * 8

		mask = ((1 << (byte_end_pos - byte_start_pos)) - 1) << (8 - byte_end_pos)
		shift = 8 - byte_end_pos - (end_pos - next_pos)

		# build getter
		cur_getter = f"((x)[{byte_index}])"
		if mask != 0xFF:
			cur_getter = f"({cur_getter} & 0x{mask:02x})"
		if shift > 0:
			cur_getter = f"({cur_getter} >> {shift})"
		elif shift < 0:
			cur_getter = f"({cur_getter} << {-shift})"
		getter_parts.append(cur_getter)

		# build setter
		cur_setter = f"(x)[{byte_index}] = "
		if mask != 0xFF:
			cur_setter += f"(((x)[{byte_index}]) & 0x{(~mask) & 0xFF:02x}) | "
		new_val = "(v)"
		if shift > 0:
			new_val = f"({new_val} << {shift})"
		elif shift < 0:
			new_val = f"({new_val} >> {-shift})"
		new_val = f"({new_val} & 0x{mask:02x})"
		cur_setter += new_val
		setter_parts.append(f"{cur_setter}; ")

		pos = next_pos

	getter = " | ".join(getter_parts)
	setter = "".join(setter_parts)
	return getter, setter


def generate_bit_field_macros(input_path: Path) -> None:
	output_path = input_path.with_suffix(".h")
	script_name = Path(__file__).name
	preprocessor_macro = f"__{input_path.stem.upper()}_H__"

	lines = input_path.read_text(encoding="utf-8").splitlines()

	result = [
		f"// generated by {script_name} from {input_path.name}\n",
		"// clang-format off\n",
		f"#ifndef {preprocessor_macro}\n",
		f"#define {preprocessor_macro}\n\n",
	]

	struct_name = None
	cur_pos = 0

	for raw_line in lines:
		line = raw_line.split("//", 1)[0]
		if not line.strip():
			continue

		if not line.startswith("\t"):
			if struct_name is not None:
				result.append(f"\n#define sizeof_{struct_name} ({(cur_pos + 7) // 8})\n\n")

			struct_name = line.strip()
			result.append(f"// {struct_name}\n")
			result.append(f"typedef unsigned char {struct_name}_t;\n\n")
			cur_pos = 0
			continue

		field_name, bit_count_str = (x.strip() for x in line.split(":"))
		bit_count = int(bit_count_str)
		getter, setter = build_field_accessor(cur_pos, bit_count)

		result.append(f"#define {struct_name}_get_{field_name}(x) ({getter})\n")
		result.append(f"#define {struct_name}_set_{field_name}(x, v) {{ {setter}}}\n")
		cur_pos += bit_count

	if struct_name is not None:
		result.append(f"\n#define sizeof_{struct_name} ({(cur_pos + 7) // 8})\n\n")

	result.append(f"#endif // {preprocessor_macro}\n")

	output_path.write_text("".join(result), encoding="utf-8")


def main() -> None:
	args = parse_args()
	generate_bit_field_macros(args.input_file)


if __name__ == "__main__":
	main()
