#!/usr/bin/env python3

import argparse
import string
from pathlib import Path


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description="Calculate ISO 639-3 language code hash parameters.")
	parser.add_argument(
		"-i", "--input-file",
		type=Path,
		default=Path(__file__).resolve().parents[1] / "vod" / "languages_x.h",
		help="Path to languages_x.h header file (default: ../vod/languages_x.h)",
	)
	return parser.parse_args()


def parse_language_codes(languages_header_path: Path) -> set[str]:
	codes = set()
	for line in languages_header_path.read_text(encoding="utf-8").splitlines():
		if not line.startswith("LANG("):
			continue
		parts = line.split(",")
		codes.add(parts[3].split('"')[1])
		if parts[2].strip() != "NULL":
			codes.add(parts[2].split('"')[1])
	return codes


def encode_lang_code(code: str) -> int:
	return (
		(((ord(code[0]) - 96) & 0x1F) << 10)
		| (((ord(code[1]) - 96) & 0x1F) << 5)
		| ((ord(code[2]) - 96) & 0x1F)
	)


def find_min_hash_size(int_codes: list[int]) -> int:
	hash_size = max(len(int_codes), 1)
	while len({code % hash_size for code in int_codes}) != len(int_codes):
		hash_size += 1
	return hash_size


def generate_language_hash_table(languages_header_path: Path) -> str:
	codes = parse_language_codes(languages_header_path)

	sizes = [
		find_min_hash_size([encode_lang_code(c) for c in codes if c.startswith(letter)])
		for letter in string.ascii_lowercase
	]

	script_name = Path(__file__).name
	output = [
		f"// generated by {script_name}",
		"// clang-format off\n",
		f"#define ISO639_3_HASH_TOTAL_SIZE ({sum(sizes)})\n",
		"static const language_hash_offsets_t iso639_3_hash_offsets[] = {",
	]

	pos = 0
	for size in sizes:
		output.append(f"\t{{{pos}, {size}}},")
		pos += size
	output.append("};\n")

	return "\n".join(output)


def main() -> None:
	args = parse_args()
	print(generate_language_hash_table(args.input_file), end="")


if __name__ == "__main__":
	main()
