name: CI

on:
  - push
  - pull_request

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: ${{ matrix.compiler }} with ${{ matrix.confargs }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang-18
          - gcc-13
        confargs:
          - module
          - dynamic-module
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential \
            clang-18 \
            gcc-13 \
            python3 \
            libssl-dev \
            libpcre3-dev \
            libxml2-dev \
            curl \
            unzip \
            libopencore-amrwb0 \
            libopencore-amrnb0 \
            libass9 \
            libgsm1 \
            libmp3lame0 \
            libjpeg9 \
            libspeex1 \
            libtheora0 \
            libva2 \
            libvpx9 \
            libxvidcore4 \
            libnuma1 \
            libvdpau1 \
            libfdk-aac2 \
            libva-drm2 \
            libva-x11-2 \
            libvorbisfile3 \
            libopenjp2-7 \
            libzvbi0 \
            libx264-164 \
            libx265-199 \
            libxcb1-dev \
            libxcb-shm0-dev \
            libvorbisenc2 \
            libavcodec-dev \
            libavfilter-dev \
            libswscale-dev
      - run: ./ci_build.sh --add-${{ matrix.confargs }}=../nginx-vod-module
      - run: |
          cd /tmp/nginx
          sudo make install
      - run: /sbin/nginx -V
      - run: |
          cd test/bitset
          NGX_ROOT=/tmp/nginx VOD_ROOT=../../ bash build.sh
          ./bitsettest
